repos:
  # Fix end of files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - '--fix=lf'

  # Lint and format
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.11
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]

      # Run the formatter.
      - id: ruff-format

  # Static type-checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.17.1'
    hooks:
      - id: mypy
        additional_dependencies: []

  # Sort imports alphabetically
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
