name: Continuous integration
on: push
jobs:
  code_check:
    name: Code check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install pipenv
        run: pip install pipenv
      - name: Check code formatting
        run: |
          pipenv install pre_commit
          pipenv run python -m pre_commit run --all-files
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        qgis_version: [release-3_16, release-3_22, release-3_28, final-3_36_1]
    env:
      QGIS_TEST_VERSION: ${{ matrix.qgis_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run tests
        run: |
          docker compose -f .docker/docker-compose.yml run qgis /usr/src/.docker/run-docker-tests.sh
  test_packaging:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            submodules: recursive
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.8
            cache: 'pip'
        - name: Install toolchain
          run: pip install build
        - name: Package with build
          run:  python -m build
        - name: Install with pip
          run: pip install .
