name: Continuous integration
on: push
jobs:
  code_check:
    name: Code check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install pipenv
        run: pip install pipenv
      - name: Check code formatting
        run: |
          pipenv install pre_commit
          pipenv run python -m pre_commit run --all-files
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        qgis_version: [release-3_16, release-3_22, release-3_28, latest]
    env:
      QGIS_TEST_VERSION: ${{ matrix.qgis_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Test on QGIS LTR 3.
        run: |
          docker-compose -f .docker/docker-compose.yml run qgis /usr/src/.docker/run-docker-tests.sh
