name: Continuous integration
on: push
jobs:
  code_check:
    name: Code check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6

      - name: Install pipenv
        run: pip install pipenv

      - name: Check code formatting
        run: |
          pipenv install pre_commit
          pipenv run python -m pre_commit run --all-files

  pyqt6-check:
    name: PyQt6 compatibility check
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/qgis/pyqgis4-checker:main-ubuntu
    steps:
      - name: Get source code
        uses: actions/checkout@v6

      - name: Check PyQt5 to PyQt6 compatibility
        run: |
          pyqt5_to_pyqt6.py --dry_run libqfieldsync/
          pyqt5_to_pyqt6.py --logfile pyqt6_checker.log libqfieldsync/

      - name: Upload script report if script fails
        uses: actions/upload-artifact@v6
        if: ${{ failure() }}
        with:
          name: pyqgis4-checker-report
          path: pyqt6_checker.log
          retention-days: 7

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        qgis_version: [release-3_22, release-3_28, final-3_36_1]
    env:
      QGIS_TEST_VERSION: ${{ matrix.qgis_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Run tests
        run: |
          docker compose -f .docker/docker-compose.yml run qgis /usr/src/.docker/run-docker-tests.sh
  test_packaging:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v6
          with:
            submodules: recursive

        - name: Setup Python
          uses: actions/setup-python@v6

        - name: Install toolchain
          run: pip install build

        - name: Package with build
          run:  python -m build

        - name: Install with pip
          run: pip install .
